# Generated by Django 5.0.3 on 2024-05-09 05:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_customuser_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="resident",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="worker",
            field=models.BooleanField(default=False),
        ),
    ]
