# Generated by Django 5.0.3 on 2024-05-07 08:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RepairProposal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField(verbose_name="Описание проблемы")),
                (
                    "status",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "Открыта"), (1, "Выполняется"), (2, "Закрыта")],
                        verbose_name="Статус заявки",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создана"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Автор заявки",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заявка на ремонт",
                "verbose_name_plural": "Заявки на ремонт",
            },
        ),
    ]
