# Generated by Django 5.0.3 on 2024-05-01 09:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("duties", "0002_kitchendutyconfig_alter_kitchenduty_people"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SwapDutiesRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_duty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="initialized_swap_duties_requests",
                        to="duties.kitchenduty",
                        verbose_name="Дежурство инициатора заявки",
                    ),
                ),
                (
                    "first_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="initialized_swap_duties_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Инициатор заявки",
                    ),
                ),
                (
                    "second_duty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addressed_swap_duties_requests",
                        to="duties.kitchenduty",
                        verbose_name="Дежурство цели заявки",
                    ),
                ),
                (
                    "second_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addressed_swap_duties_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Цель заявки",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SwapPeopleRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "current_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="initialized_swap_people_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "duty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="swap_people_requests",
                        to="duties.kitchenduty",
                    ),
                ),
                (
                    "to_swap",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addressed_swap_people_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
