# Generated by Django 5.0.3 on 2024-05-09 06:17

import core.apps.common.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("duties", "0003_swapdutiesrequest_swappeoplerequest"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="kitchenduty",
            name="people",
            field=models.ManyToManyField(
                related_name="kitchen_duties",
                to=settings.AUTH_USER_MODEL,
                validators=[core.apps.common.validators.user_is_resident],
                verbose_name="Ответственные",
            ),
        ),
    ]
