# Generated by Django 5.0.3 on 2024-05-09 07:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("duties", "0004_alter_kitchenduty_people"),
    ]

    operations = [
        migrations.AddField(
            model_name="swapdutiesrequest",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Дата создания",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="swapdutiesrequest",
            name="declined",
            field=models.BooleanField(default=False, verbose_name="Отклонена?"),
        ),
        migrations.AddField(
            model_name="swappeoplerequest",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="Дата создания",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="swappeoplerequest",
            name="declined",
            field=models.BooleanField(default=False, verbose_name="Отклонена?"),
        ),
    ]
