# Generated by Django 5.0.3 on 2024-05-10 09:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("duties", "0005_swapdutiesrequest_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="swapdutiesrequest",
            name="canceled",
            field=models.BooleanField(default=False, verbose_name="Отменена?"),
        ),
        migrations.AddField(
            model_name="swappeoplerequest",
            name="canceled",
            field=models.BooleanField(default=False, verbose_name="Отменена?"),
        ),
    ]
