# Generated by Django 5.0.3 on 2024-06-25 09:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("duties", "0008_alter_kitchenduty_people"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="swapdutiesrequest",
            options={
                "verbose_name": "Запрос на обмен",
                "verbose_name_plural": "Запросы на обмен",
            },
        ),
    ]
