version: '3.9'

services:
  dorm-backend:
    build:
      context: ..
      dockerfile: Dockerfile
      target: production
    container_name: main-app
    expose:
      - ${DJANGO_PORT}
    volumes:
      - static_volume:/app/static
    env_file:
     - ../.env
    depends_on:
     - postgres_dorm

volumes:
  static_volume: