# Generated by Django 5.0.3 on 2024-04-17 05:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='laundryrecord',
            name='record_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата записи'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='laundryrecord',
            name='time_end',
            field=models.TimeField(verbose_name='Окончание записи'),
        ),
        migrations.AlterField(
            model_name='laundryrecord',
            name='time_start',
            field=models.TimeField(verbose_name='Начало записи'),
        ),
    ]
