# Generated by Django 5.0.3 on 2024-04-17 05:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundry', '0002_laundryrecord_record_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='laundryrecord',
            options={'verbose_name': 'Запись прачечной', 'verbose_name_plural': 'Записи прачечной'},
        ),
        migrations.AlterField(
            model_name='laundryrecord',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Чья запись'),
        ),
    ]
