# Generated by Django 5.0.3 on 2024-05-09 06:17

import core.apps.common.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rooms", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="roomrecord",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                validators=[core.apps.common.validators.user_is_staff],
                verbose_name="Ответственный",
            ),
        ),
    ]
